name: CI-main

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Maven build
        run: echo Hello, world!
  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Maven verify
        run: echo Hello, world!
  quality:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: Analysis Sonarqube to branch main
        run: echo Hello, world!

      - name: Analysis Fortify to branch main
        run: echo Hello, world!

      - name: Analysis Advance Security to branch main
        run: echo Hello, world!

  manual-approval:
    name: manual approval
    runs-on: ubuntu-latest
    needs: quality
    if: success()

    permissions:
      issues: write
      contents: read

    steps: 
      - name: Await for manual approval
        uses: trstringer/manual-approval@v1
        with:
          minimum-approvals: 1
          issue-title: "Gerar versão?"
          issue-body: "Deseja gerar versão?"

    
  versioning:
    runs-on: ubuntu-latest
    needs: manual-approval

    steps:
      - uses: actions/checkout@v4

      - name: Figure out next version
        run: echo Hello, world!

      - name: Update version
        run: echo Hello, world!

      - name: Generate changelog
        run: echo Hello, world!

      - name: Commit and Tagging
        run: echo Hello, world!
