name: CI-main

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Maven build
        run: echo Hello, world!
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Maven verify
        run: echo Hello, world!
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Analysis Sonarqube to branch main
        run: echo Hello, world!
  fortify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Analysis Fortify to branch main
        run: echo Hello, world!
  advance-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Analysis Advance Security to branch main
        run: echo Hello, world!
